name: "1 - BUILD & PR"

on:
  push:
    branches:
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Substitua pela sua região

    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Inicializar Terraform
      run: terraform init

    - name: Validar configurações do Terraform
      run: terraform validate

    - name: Planejar alterações
      run: terraform plan -var-file="hom/vars.tfvars" -out=tfplan

  open-pr:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        delete-branch: false
        base: ${{ steps.tag_version.outputs.new_tag }}
        branch: main
        title: "Merge da versão ${{ steps.tag_version.outputs.new_tag }} para main"
        body: "Este pull request foi criado automaticamente para mesclar a versão ${{ steps.tag_version.outputs.new_tag }} na branch main."