name: "1 - BUILD & PR"

on:
  push:
    branches:
      - release/*

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Substitua pela sua região

    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Inicializar Terraform
      run: terraform init

    - name: Validar configurações do Terraform
      run: terraform validate

    - name: Planejar alterações
      run: terraform plan -var-file="prod/vars.tfvars" -out=tfplan