name: Gerenciar Terraform

on:
  push:
    branches:
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Substitua pela sua região

    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Inicializar Terraform
      run: terraform init

    - name: Validar configurações do Terraform
      run: terraform validate

    - name: Planejar alterações
      run: terraform plan -var-file="hom/vars.tfvars" -out=tfplan

    - name: Criar Branch de Release
      if: github.ref == 'refs/heads/develop'
      run: |
        git checkout -b release/${{ github.run_number }}
        git push origin release/${{ github.run_number }}

    - name: Criar Pull Request automaticamente
      if: github.ref == 'refs/heads/develop'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: release/${{ github.run_number }}
        title: "Merge da branch de main para release"
        body: "Este pull request foi criado automaticamente para mesclar a branch de main para a branch de release."