name: Gerenciar Terraform

on:
  push:
    branches:
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      
    - name: Configurar AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Substitua pela sua região

    - name: Inicializar Terraform
      run: terraform init

    - name: Validar configurações do Terraform
      run: terraform validate

    - name: Planejar alterações
      run: terraform plan -out=tfplan

    - name: Criar Branch de Release
      if: github.ref == 'refs/heads/develop'
      run: |
        git checkout -b release/${{ github.run_number }}
        git push origin release/${{ github.run_number }}
